import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { provider } from "./GlobalRedux/store"; // Import the Providers component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Wrap the body content with the Providers component */}
      <body className={inter.className}>
        <provider>{children}</provider>
      </body>
    </html>
  );
}
